package config

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	fileYAML = "gflow.yaml"
	fileBash = ".gflow.conf"
)

// Load reads gflow.yaml (preferred) or .gflow.conf (bash-compat) from root.
// root="" uses the current working directory.
func Load(root string) (*Config, error) {
	if root == "" {
		var err error
		root, err = os.Getwd()
		if err != nil {
			return nil, err
		}
	}

	yamlPath := filepath.Join(root, fileYAML)
	bashPath := filepath.Join(root, fileBash)

	cfg := defaults()

	switch {
	case fileExists(yamlPath):
		if err := loadYAML(yamlPath, &cfg); err != nil {
			return nil, fmt.Errorf("load %s: %w", fileYAML, err)
		}
	case fileExists(bashPath):
		if err := loadBash(bashPath, &cfg); err != nil {
			return nil, fmt.Errorf("load %s: %w", fileBash, err)
		}
	default:
		// no config file — use defaults, discover modules from .gitmodules
	}

	return &cfg, nil
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

// loadYAML parses gflow.yaml into cfg.
func loadYAML(path string, cfg *Config) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	dec := yaml.NewDecoder(f)
	dec.KnownFields(true)
	return dec.Decode(cfg)
}

// Bash-compat regex parser — supports the shapes emitted by legacy gflow config generator.
// Supported:
//
//	KEY=value
//	KEY="value"
//	KEY=(a b c)
//	add_path_alias "key" "paths"
//
// No eval, no subshell. Unsupported shapes are flagged with a clear error.
var (
	reSimple  = regexp.MustCompile(`^([A-Z_]+)=([^("$].*)$`)
	reQuoted = regexp.MustCompile(`^([A-Z_]+)="(.*)"$`)
	reArray  = regexp.MustCompile(`^([A-Z_]+)=\(([^)]*)\)$`)
	reAlias  = regexp.MustCompile(`^add_path_alias\s+"([^"]+)"\s+"([^"]+)"$`)
	reComment = regexp.MustCompile(`^\s*#`)
	reBlank   = regexp.MustCompile(`^\s*$`)
)

func loadBash(path string, cfg *Config) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	if cfg.Aliases == nil {
		cfg.Aliases = make(map[string][]string)
	}

	scanner := bufio.NewScanner(f)
	lineNo := 0
	for scanner.Scan() {
		line := scanner.Text()
		lineNo++

		if reComment.MatchString(line) || reBlank.MatchString(line) {
			continue
		}

		switch {
		case reAlias.MatchString(line):
			m := reAlias.FindStringSubmatch(line)
			key, paths := m[1], strings.Fields(m[2])
			cfg.Aliases[key] = append(cfg.Aliases[key], paths...)

		case reArray.MatchString(line):
			m := reArray.FindStringSubmatch(line)
			applyBashVar(cfg, m[1], strings.Fields(m[2]))

		case reQuoted.MatchString(line):
			m := reQuoted.FindStringSubmatch(line)
			applyBashVar(cfg, m[1], []string{m[2]})

		case reSimple.MatchString(line):
			m := reSimple.FindStringSubmatch(line)
			applyBashVar(cfg, m[1], []string{m[2]})

		default:
			return fmt.Errorf(
				"%s:%d: unsupported .gflow.conf shape %q — run `gflow config migrate` to convert to gflow.yaml",
				path, lineNo, line,
			)
		}
	}
	return scanner.Err()
}

func applyBashVar(cfg *Config, key string, vals []string) {
	switch key {
	case "MODULES":
		cfg.Modules = vals
	case "PARALLEL_EXECUTION":
		cfg.Parallel = len(vals) > 0 && vals[0] == "true"
	case "DRY_RUN":
		// ignore; runtime flag controls this
	case "DEBUG":
		cfg.Debug = len(vals) > 0 && vals[0] == "true"
	case "INCLUDE_ROOT":
		cfg.NoRoot = len(vals) > 0 && vals[0] == "false"
	case "REMOTE_NAME":
		if len(vals) > 0 {
			cfg.Remote = vals[0]
		}
	// Intentionally ignored phantom vars from legacy:
	case "BRANCH_TYPES", "GITFLOW_VARIANT", "FINISH_OPTIONS", "GIT_COMMANDS",
		"CONFIG_FILE", "PATH_ALIASES_KEYS", "PATH_ALIASES_VALUES":
	}
}

// EmitYAML writes gflow.yaml.
func EmitYAML(cfg *Config, root string) error {
	if root == "" {
		var err error
		root, err = os.Getwd()
		if err != nil {
			return err
		}
	}
	f, err := os.Create(filepath.Join(root, fileYAML))
	if err != nil {
		return err
	}
	defer f.Close()
	enc := yaml.NewEncoder(f)
	enc.SetIndent(2)
	return enc.Encode(cfg)
}

// EmitBash writes .gflow.conf in the legacy bash format.
func EmitBash(cfg *Config, root string) error {
	if root == "" {
		var err error
		root, err = os.Getwd()
		if err != nil {
			return err
		}
	}
	f, err := os.Create(filepath.Join(root, fileBash))
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	fmt.Fprintf(w, "# Generated by gflow config --bash\n\n")
	fmt.Fprintf(w, "MODULES=(%s)\n", strings.Join(cfg.Modules, " "))
	fmt.Fprintf(w, "REMOTE_NAME=%s\n", cfg.Remote)
	if cfg.Parallel {
		fmt.Fprintf(w, "PARALLEL_EXECUTION=true\n")
	}
	if cfg.Debug {
		fmt.Fprintf(w, "DEBUG=true\n")
	}
	for key, paths := range cfg.Aliases {
		fmt.Fprintf(w, "add_path_alias %q %q\n", key, strings.Join(paths, " "))
	}
	return w.Flush()
}

// Migrate converts .gflow.conf → gflow.yaml.
func Migrate(root string) error {
	if root == "" {
		var err error
		root, err = os.Getwd()
		if err != nil {
			return err
		}
	}
	bashPath := filepath.Join(root, fileBash)
	if !fileExists(bashPath) {
		return errors.New(".gflow.conf not found")
	}
	cfg := defaults()
	if err := loadBash(bashPath, &cfg); err != nil {
		return err
	}
	return EmitYAML(&cfg, root)
}

// Validate checks config for semantic errors.
func Validate(cfg *Config) error {
	return validate(cfg)
}
